-- MySQL Script generated by MySQL Workbench
-- Fri Mar 20 16:03:10 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema carteira_pet
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema carteira_pet
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `carteira_pet` DEFAULT CHARACTER SET utf8 ;
USE `carteira_pet` ;

-- -----------------------------------------------------
-- Table `carteira_pet`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `carteira_pet`.`usuario` ;

CREATE TABLE IF NOT EXISTS `carteira_pet`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(50) NOT NULL,
  `senha` VARCHAR(250) NOT NULL,
  `criado_em` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `atualizado_em` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `carteira_pet`.`tutor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `carteira_pet`.`tutor` ;

CREATE TABLE IF NOT EXISTS `carteira_pet`.`tutor` (
  `id_tutor` INT NOT NULL AUTO_INCREMENT,
  `tutor` VARCHAR(100) NOT NULL COMMENT 'Nome do tutor',
  `email` VARCHAR(100) NOT NULL,
  `celular` VARCHAR(20) NULL,
  `telefone` VARCHAR(20) NULL,
  `logradouro` VARCHAR(50) NOT NULL,
  `numero_logradouro` VARCHAR(10) NULL,
  `complemento` VARCHAR(20) NULL,
  `bairro` VARCHAR(50) NOT NULL,
  `cidade` VARCHAR(50) NOT NULL,
  `uf` VARCHAR(2) NOT NULL COMMENT 'Unidade da Federação, exemplo: SP, PE, SC',
  `cep` VARCHAR(9) NULL,
  `usuario_id` INT NOT NULL,
  `criado_em` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `atualizado_em` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_tutor`),
  INDEX `idx_tutor` (`tutor` ASC) VISIBLE,
  INDEX `fk_tutor_usuario_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_tutor_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `carteira_pet`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `carteira_pet`.`especie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `carteira_pet`.`especie` ;

CREATE TABLE IF NOT EXISTS `carteira_pet`.`especie` (
  `id_especie` INT NOT NULL AUTO_INCREMENT,
  `especie` VARCHAR(50) NOT NULL COMMENT 'Descrição da espécie, exemplo: Ave, Canina, Felina',
  PRIMARY KEY (`id_especie`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `carteira_pet`.`pet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `carteira_pet`.`pet` ;

CREATE TABLE IF NOT EXISTS `carteira_pet`.`pet` (
  `id_pet` INT NOT NULL AUTO_INCREMENT,
  `pet` VARCHAR(50) NOT NULL,
  `raca` VARCHAR(50) NULL,
  `sexo` ENUM('M', 'F') CHARACTER SET 'cp1251' NOT NULL COMMENT 'Responda apenas \"M\" ou \"F\"',
  `data_nascimento` DATE NULL,
  `castrado` ENUM('S', 'N') NULL COMMENT 'Responda apena \"S\" ou \"N\"',
  `data_castracao` DATE NULL,
  `tutor_id` INT NOT NULL,
  `especie_id` INT NOT NULL,
  `criado_em` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `atualizado_em` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_pet`),
  INDEX `fk_pet_tutor_idx` (`tutor_id` ASC) VISIBLE,
  INDEX `fk_pet_especie1_idx` (`especie_id` ASC) VISIBLE,
  INDEX `pet_idx` (`pet` ASC) VISIBLE,
  CONSTRAINT `fk_pet_tutor`
    FOREIGN KEY (`tutor_id`)
    REFERENCES `carteira_pet`.`tutor` (`id_tutor`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_pet_especie1`
    FOREIGN KEY (`especie_id`)
    REFERENCES `carteira_pet`.`especie` (`id_especie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `carteira_pet`.`veterinario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `carteira_pet`.`veterinario` ;

CREATE TABLE IF NOT EXISTS `carteira_pet`.`veterinario` (
  `id_veterinario` INT NOT NULL AUTO_INCREMENT,
  `veterinario` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NULL,
  `celular` VARCHAR(16) NULL,
  `telefone` VARCHAR(16) NULL,
  `logradouro` VARCHAR(50) NOT NULL,
  `numero_endereco` VARCHAR(10) NULL,
  `bairro` VARCHAR(50) NOT NULL,
  `cidade` VARCHAR(50) NOT NULL,
  `uf` VARCHAR(2) NOT NULL COMMENT 'Unidade da Federação, exemplo: SP, PE, SC',
  `cep` VARCHAR(9) NULL,
  `criado_em` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `atualizado_em` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_veterinario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `carteira_pet`.`pet_veterinario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `carteira_pet`.`pet_veterinario` ;

CREATE TABLE IF NOT EXISTS `carteira_pet`.`pet_veterinario` (
  `pet_id_pet` INT NOT NULL,
  `veterinario_id_veterinario` INT NOT NULL,
  PRIMARY KEY (`pet_id_pet`, `veterinario_id_veterinario`),
  INDEX `fk_pet_has_veterinario_veterinario1_idx` (`veterinario_id_veterinario` ASC) VISIBLE,
  INDEX `fk_pet_has_veterinario_pet1_idx` (`pet_id_pet` ASC) VISIBLE,
  CONSTRAINT `fk_pet_has_veterinario_pet1`
    FOREIGN KEY (`pet_id_pet`)
    REFERENCES `carteira_pet`.`pet` (`id_pet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pet_has_veterinario_veterinario1`
    FOREIGN KEY (`veterinario_id_veterinario`)
    REFERENCES `carteira_pet`.`veterinario` (`id_veterinario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `carteira_pet`.`vacina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `carteira_pet`.`vacina` ;

CREATE TABLE IF NOT EXISTS `carteira_pet`.`vacina` (
  `id_vacina` INT NOT NULL AUTO_INCREMENT,
  `vacina` VARCHAR(70) NOT NULL,
  `obs_vacina` VARCHAR(200) NULL,
  `data_aplicacao` DATE NOT NULL,
  `pet_id` INT NOT NULL,
  `veterinario_id` INT NOT NULL,
  `criado_em` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `atualizado_em` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_vacina`),
  INDEX `fk_vacina_pet1_idx` (`pet_id` ASC) VISIBLE,
  INDEX `fk_vacina_veterinario1_idx` (`veterinario_id` ASC) VISIBLE,
  CONSTRAINT `fk_vacina_pet1`
    FOREIGN KEY (`pet_id`)
    REFERENCES `carteira_pet`.`pet` (`id_pet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vacina_veterinario1`
    FOREIGN KEY (`veterinario_id`)
    REFERENCES `carteira_pet`.`veterinario` (`id_veterinario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
